services:
  user-service:
    container_name: user-service-dev
    build:
      context: ../templates/back/services/_template
      dockerfile: Dockerfile.dev
    command: yarn dev
    ports:
      - "${USER_SERVICE_HTTP_PORT}:3000"
      - "${USER_SERVICE_TCP_PORT}:3004"
    environment:
      NODE_ENV: ${NODE_ENV}
      SERVICE_PORT: ${USER_SERVICE_HTTP_PORT}
      TCP_PORT: ${USER_SERVICE_TCP_PORT}
      USER_DB_PORT: ${USER_DB_PORT}
      USER_DB_USER: ${USER_DB_USER}
      USER_DB_PASSWORD: ${USER_DB_PASSWORD}
      USER_DB_NAME: ${USER_DB_NAME}
    networks:
      - goosee_net
    depends_on:
      - user-service-db

  user-service-db:
    container_name: user-service-db-dev
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${USER_DB_USER}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
      POSTGRES_DB: ${USER_DB_NAME}
    ports:
      - "${USER_DB_PORT}:5432"
    volumes:
      - user-service-data:/var/lib/postgresql/data
    networks:
      - goosee_net

networks:
  goosee_net:
    name: goosee_net

volumes:
  user-service-data:
