services:
    goosee-front-dev:
        container_name: goosee-front-dev
        build:
            context: ../..
            dockerfile: templates/front/Dockerfile.dev
        command: yarn dev
        ports:
            - "${NEXT_PORT}:${NEXT_PORT}"
        environment:
            NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
            NODE_ENV: ${NODE_ENV}
        networks:
            - goosee_net
