services:
    api-gateway:
        container_name: goosee-api-gateway-dev
        build:
            context: ../templates/back/api-gateway
            dockerfile: Dockerfile.dev
        command: yarn dev
        ports:
            - "${API_GATEWAY_HTTP_PORT}:3000"
            - "${API_GATEWAY_TCP_PORT}:3002"
        environment:
            NODE_ENV: ${NODE_ENV}
            SERVICE_PORT: ${API_GATEWAY_HTTP_PORT}
            TCP_PORT: ${API_GATEWAY_TCP_PORT}
            USER_SERVICE_HOST: user-service
            USER_SERVICE_TCP_PORT: ${USER_SERVICE_TCP_PORT}
        networks:
            - goosee_net
        depends_on:
            - user-service

networks:
    goosee_net:
        name: goosee_net
