services:
  goosee-rabbitmq-dev:
    image: rabbitmq:management
    container_name: goosee-rabbitmq-dev
    hostname: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_UI_PORT}:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - goosee_net

  goosee-adminer-dev:
    container_name: goosee-adminer-dev
    image: adminer
    restart: unless-stopped
    ports:
      - "${ADMINER_PORT}:8080"
    networks:
      - goosee_net

  goosee-mailhog-dev:
    container_name: goosee-mailhog-dev
    image: mailhog/mailhog:v1.0.1
    restart: unless-stopped
    ports:
      - "${MAILHOG_SMTP_PORT}:1025"
      - "${MAILHOG_UI_PORT}:8025"
    networks:
      - goosee_net

  minio:
    image: minio/minio:latest
    container_name: goosee-minio-dev
    restart: unless-stopped
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - goosee_net
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  goosee_net:
    name: goosee_net
    driver: bridge

volumes:
  minio_data:
  rabbitmq_data:
