services:
    goosee-front-dev:
        container_name: goosee-front-dev
        build:
            context: ../../templates/front
            dockerfile: Dockerfile.dev
        command: ["node", "/app/node_modules/next/dist/bin/next", "dev"]
        ports:
            - "3000:3000"
        environment:
            NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
            NODE_ENV: ${NODE_ENV}
        networks:
            - goosee_net
