services:
  goosee-api-gateway-dev:
    container_name: goosee-api-gateway-dev
    build:
      context: ../../templates/back/api-gateway
      dockerfile: Dockerfile.dev
    command: yarn dev
    ports:
      - "${API_GATEWAY_PORT}:${API_GATEWAY_PORT}"
    environment:
      NODE_ENV: ${NODE_ENV}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
      USER_SERVICE_HOST: ${USER_SERVICE_HOST}
    depends_on:
      - goosee-user-service-dev
    networks:
      - goosee_net

  goosee-user-service-dev:
    container_name: goosee-user-service-dev
    build:
      context: ../../templates/back/services/_template
      dockerfile: Dockerfile.dev
    command: yarn dev
    environment:
      NODE_ENV: ${NODE_ENV}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT}
    expose:
      - "${USER_SERVICE_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost ${USER_SERVICE_PORT}"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s
    networks:
      - goosee_net

networks:
  goosee_net:
    driver: bridge
