services:
    front-prod:
        build:
            context: ../templates/front
            dockerfile: Dockerfile
        command: yarn start
        ports:
            - "3000:3000"
        environment:
            NEXT_PUBLIC_API_GATEWAY_URL: ${NEXT_PUBLIC_API_GATEWAY_URL}
            NODE_ENV: ${NODE_ENV}
        networks:
            - goosee_net
