# Copier ce fichier en secrets.yaml et remplir les valeurs réelles.
# Ce fichier est commité. secrets.yaml est dans .gitignore.
apiVersion: v1
kind: Secret
metadata:
  name: goosee-secrets
  namespace: goosee-dev
type: Opaque
stringData:
  # User DB
  USER_DB_USER: ""
  USER_DB_PASSWORD: ""
  USER_DB_NAME: ""

  # Auth DB
  AUTH_DB_USER: ""
  AUTH_DB_PASSWORD: ""
  AUTH_DB_NAME: ""

  # Page DB
  PAGE_DB_USER: ""
  PAGE_DB_PASSWORD: ""
  PAGE_DB_NAME: ""

  # RabbitMQ
  RABBITMQ_URL: ""
  RABBITMQ_ERLANG_COOKIE: ""

  # MinIO
  MINIO_ROOT_USER: ""
  MINIO_ROOT_PASSWORD: ""

  # SMTP (vide en dev, Mailhog n'a pas d'auth)
  SMTP_USER: ""
  SMTP_PASSWORD: ""
