apiVersion: v1
kind: Service
metadata:
  name: SERVICE_NAME
  namespace: goosee-dev
spec:
  selector:
    app: SERVICE_NAME
  ports:
    - port: SERVICE_PORT
      targetPort: SERVICE_PORT
  type: ClusterIP
