FROM node:22-alpine

RUN corepack enable && corepack prepare yarn@1.22.22 --activate
RUN yarn config set network-timeout 600000 -g

WORKDIR /usr/src/app

COPY package.json yarn.lock ./
COPY templates/front/package.json ./templates/front/package.json
RUN yarn install --frozen-lockfile --network-timeout 600000

COPY templates/front ./templates/front

WORKDIR /usr/src/app/templates/front

ENV NODE_ENV=development
ENV PORT=3000

EXPOSE 3000

CMD ["yarn", "dev"]
