FROM node:22-alpine

RUN corepack enable && corepack prepare yarn@1.22.22 --activate
RUN yarn config set network-timeout 600000 -g

WORKDIR /usr/src/app

COPY package.json yarn.lock ./
COPY templates/back/api-gateway/package.json ./templates/back/api-gateway/package.json
RUN yarn install --frozen-lockfile --network-timeout 600000

COPY templates/back/api-gateway ./templates/back/api-gateway

WORKDIR /usr/src/app/templates/back/api-gateway

EXPOSE 3000

CMD ["yarn", "dev"]
